# Question

This code snippet makes a fetch to get the first todo item from the JSON placeholder API. Or at least it tries to.

What is wrong with this code? 

Describe how async/await helps us avoid this mistake.

```js
fetch('https://jsonplaceholder.typicode.com/todos/1')
  .then(response => {
    if (!response.ok) throw new Error('Fetch failed!');
    response.json();
  })
  .then(json => console.log(json))
  .catch(err => console.log(err))
```

You can run this code of course, but try not to! Try to figure out the issue on your own.

# Answer
The problem is `response.json();` where you need to `return response.json();` to returns a promise, but the code does not wait for this promise to resolve before attempting to use its result. This means that json in the second .then block is actually undefined.
In async/await, you don't need to return promise. `await` makes it explicit that response.json() is asynchronous and needs to be awaited. This reduces the likelihood of forgetting to return or handle the promise.

```js
async function fetchTodo() {
  try {
    const response = await fetch('https://jsonplaceholder.typicode.com/todos/1');
    if (!response.ok) throw new Error('Fetch failed!');
    const json = await response.json(); // Await the promise
    console.log(json);
  } catch (err) {
    console.log(err);
  }
}

fetchTodo();

```

# Teacher Feedback
Score: 3/3
